version: '3.9'
# NOTE Wait for atleast 5 min before else you will get ERROR_NO_RESPONSE at localhost:5050
# Steps to COnnection
# 1. Go to https://localhost:5050/browser
# 2. Ener the Credential specified below for pgadmin
# 3. Create new server
# 4. Host name should be 'host.docker.internal'
# 5. Provide DB password
# 6. Connect
services:
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=gagan
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=taskmanagement
    ports:
      - '5432:5432'
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4:5.4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
