### Fetch All tasks
GET http://localhost:3000/tasks
Authorization: Bearer [Token]

### Fetch By ID
GET http://localhost:3000/tasks/{id}
Authorization: Bearer [Token]

### Fetch with Query
GET http://localhost:3000/tasks?status=OPEN&search=lear
Authorization: Bearer [Token]

### Fetch with Query - Invalid
GET http://localhost:3000/tasks?status=OPE
Authorization: Bearer [Token]

### Create a new task
POST http://localhost:3000/tasks
Authorization: Bearer [Token]
Content-Type: application/json

{
  "title": "Learn NestJS",
  "description": "It is a backend JS aplication"
}

### Create a new task - Invalid request
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "description": "It is a backend JS aplication"
}

### Delete a task
DELETE http://localhost:3000/tasks/{id}
Authorization: Bearer [Token]

### Update a task
PATCH http://localhost:3000/tasks/{id}/status
Authorization: Bearer [Token]
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

### Update a task - Invalid
PATCH http://localhost:3000/tasks/{id}/status
Authorization: Bearer [Token]
Content-Type: application/json

{
  "status": "IN_PRO"
}

################################################
## Authentication
################################################


### Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "gagan",
  "password": "P@ssw0rd"
}

### Sign In
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "gagan",
  "password": "P@ssw0rd"
}

### Protected Route
POST http://localhost:3000/auth/protected
Authorization: Bearer [Token]


### Custom Decorator
POST http://localhost:3000/auth/abc
Authorization: Bearer [Token]
