### Fetch All tasks
GET http://localhost:3000/tasks

### Fetch By ID
GET http://localhost:3000/tasks/{id}

### Fetch with Query
GET http://localhost:3000/tasks?status=OPEN&search=lear

### Create a new task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Learn NestJS",
  "description": "It is a backend JS aplication"
}

### Create a new task - Invalid request
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "description": "It is a backend JS aplication"
}

### Delete a task
DELETE http://localhost:3000/tasks/{id}

### Update a task
PATCH http://localhost:3000/tasks/{id}/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}
