# All configuration non-specific o ay environment
# Specific environment that will work allong with default is specifie using NODE_ENV
server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'taskmanagement'

jwt:
  expiresIn: 3600
